server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    jdbcUrl: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    h2:
      console:
        enabled: true
  # JPA
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl.auto: validate
        format_sql: false
        physical_naming_strategy: 'com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy'
        jdbc:
          lob:
            non_contextual_creation: true
  # liquibase
  liquibase:
    change-log: 'classpath:db/liquibase-changelog-master.xml'
    contexts: 'test-data'
  # ThymeLeaf
  thymeleaf:
    template-loader-path: classpath:/templates
    suffix: .html
    cache: false
  #Actuator
  management:
    endpoints:
      web:
        exposure:
          include: info,health,metrics,loggers,beans,mappings
      health:
        show-details: always
